### ISSUE TITLE
Loose test against classic implementation

### ISSUE THREAD

**Issue by nhejazi** [tlverse/tmle3shift#16]
The [`txshift` package](https://github.com/nhejazi/txshift) provides an implementation of this same estimation procedure in the case of a simple shift (i.e., `shift_additive`) without reliance on `tmle3` machinery. The independent procedure is used as the basis for [this test](https://github.com/tlverse/tmle3shift/blob/master/tests/testthat/test-shift_additive_simple.R#L137-L141), which has been loosened as of f83eabf. This test was previously passing under the (original) more stringent criteria as of 355c29f. It seems rather unlikely that a change in this package would have caused this test to break (since no commits near or after 355c29f altered `shift_additive`); instead, it's likely this was caused by updates to dependencies, which do not currently run reverse dependency checks. This should be further investigated.

**Comment by jeremyrcoyle** [comment]
I'll make a PR to fix this real fast
