### ISSUE TITLE
Compatible with tmle3mediate? 

### ISSUE THREAD

**Issue by XinyueJia** [tlverse/tmle3shift#33]
Hello @nhejazi, I'm new to TMLE and attempting mediation analysis with continuous data. I came across your packages, tmle3mediate and tmle3shift, and believe they could be valuable for my work. However, I've encountered an issue with their support for mediators or continuous data, as they require generating a Spec term for each. It seems that I'm unable to include both Specs in a single estimation task. If this is correct, do you have any guidance on capturing causal effects in such scenarios?
![Causal](https://github.com/tlverse/tmle3shift/assets/77334755/f7471593-3182-4977-ac18-3f10c843f24a)

**Comment by nhejazi** [comment]
thanks for your interest in this package and the corresponding research they implement. this package does not support mediation analysis--and is not meant to. the `tmle3mediate` package does provide a method for causal mediation analysis with continuous treatments via https://github.com/tlverse/tmle3mediate/blob/master/R/Param_medshift.R, which is an implementation of this manuscript: https://academic.oup.com/jrsssb/article/82/3/661/7056041
